Handler Rewrite
Progressive-Victory/discord-client pull request #8
Opened 2024-01-14 20:35 UTC by bowenjw

# New Handlers
Rewrote command, interaction and event handlers for easy of use.

## Updated `packages.json`
updated all modules to updated versions
Changes brake existing code and version updated to `0.4.0`

2024-01-20 17:06 UTC, bowenjw commented
@Lewdcario please look at this when you get a chance

2024-01-25 02:02 UTC, Lewdcario requested changes
Looks very good, just nitpicking a little bit on spelling

2024-01-25 02:02 UTC, Lewdcario commented on README.md
> +Interaction objects are a genaric and can be used for any object the following is the example of a button interaction. Button interactions should be placed in the Dirctory path set in the `buttonPath
Dirctory -> directory

2024-01-25 02:02 UTC, Lewdcario commented on jest.config.ts
> +	},
This was my bad but can you remove the "x" here from tsx, this was copied over from my nextjs project

2024-01-25 02:36 UTC, Lewdcario approved these changes

2024-01-25 02:36 UTC, merged